export const salesData = [
    {
        id:1,
        name:"Bangladesh",
        amount:"$12k",
        sales_rate:"14.8%",
        image:"/images/all/bangladesh.png",
        isUp:true
    },
    {
        id:2,
        name:"Australia",
        amount:"$22k",
        sales_rate:"15.8%",
        image:"/images/all/australia.png",
        isUp:true
    },
    {
        id:3,
        name:"Canada",
        amount:"$32k",
        sales_rate:"25.8%",
        image:"/images/all/canada.png",
        isUp:false
    },
    {
        id:4,
        name:"French",
        amount:"$42k",
        sales_rate:"35.8%",
        image:"/images/all/french.png",
        isUp:true
    },
    {
        id:5,
        name:"Germany",
        amount:"$432k",
        sales_rate:"15.8%",
        image:"/images/all/germany.png",
        isUp:true
    },
    {
        id:6,
        name:"Spain",
        amount:"$42k",
        sales_rate:"18.8%",
        image:"/images/all/spain.png",
        isUp:false
    }
]

export const revinueData = [
    {
        id:1,
        name:"Facebook",
        amount:"30,567",
        isIncrease:true
    },
    {
        id:2,
        name:"Google",
        amount:"20,567",
        isIncrease:true
    },
    {
        id:3,
        name:"Twitter",
        amount:"40,567",
        isIncrease:true
    },
    {
        id:4,
        name:"Instagram",
        amount:"50,567",
        isIncrease:false
    },
    {
        id:5,
        name:"Linkedin",
        amount:"60,567",
        isIncrease:true
    },
    {
        id:6,
        name:"Youtube",
        amount:"70,567",
        isIncrease:true
    },
    {
        id:7,
        name:"Github",
        amount:"80,567",
        isIncrease:false
    },
    {
        id:8,
        name:"Dribble",
        amount:"90,567",
        isIncrease:false
    },
    {
        id:9,
        name:"Skype",
        amount:"100,567",
        isIncrease:false
    }  
]